### ISSUE TITLE
Create calibration tool for sensors

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/autoware.universe#592]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Create calibration tool for sensors.

### Purpose

Create calibration tool so that users can generate calibration parameters for sensors.
This includes: 
 - Intrinsic parameter for cameras
 - extrinsic parameter between cameras (camera-camera calibration)
 - extrinsic parameter between lidars (lidar-lidar calibration)
 - extrinsic parameter between a camera and a lidar (camera-lidar calibration)

### Definition of done

- [ ] autowarefoundation/autoware.universe#677
- [ ] autowarefoundation/autoware.universe#679
- [ ] autowarefoundation/autoware-documentation#114

**Comment by xmfcx** [comment]
https://github.com/ethz-asl/kalibr

https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_2_0_sensor_calibration_guide.md

@xmfcx fix

**Comment by mitsudome-r** [comment]
During the call, we have decided to split the tickets into a smaller task. @mitsudome-r will do work on it.

**Comment by xmfcx** [comment]
@xmfcx provide details for issues 
- https://github.com/autowarefoundation/autoware.universe/issues/677
- https://github.com/autowarefoundation/autoware.universe/issues/679
- https://github.com/autowarefoundation/autoware.universe/issues/678

**Comment by xmfcx** [comment]
Already being discussed in:
- https://github.com/autowarefoundation/autoware.universe/issues/679
- https://github.com/autowarefoundation/autoware.universe/issues/677
